name: Linux Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        swift: ["5.2", "5.1.5"]
        protobuf: ["3.11.4"]
        include:
          - protobuf: "3.11.4"
          - checksum: "6d0f18cd84b918c7b3edd0203e75569e0c8caecb1367bbbe409b45e28514f5be"
    container:
      image: swift:${{ matrix.swift }}-bionic
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main
    - name: Build
      working-directory: main
      run: make build
    - name: Test runtime
      working-directory: main
      run: make test-runtime
    # dependencies for integration tests
    - name: Update and install dependencies
      run: |
        apt-get update && apt-get install -y curl unzip automake libtool
        curl -L -O https://github.com/protocolbuffers/protobuf/releases/download/v${{ matrix.protobuf }}/protoc-${{ matrix.protobuf }}-linux-x86_64.zip
        echo '${{ matrix.checksum }}  protoc-${{ matrix.protobuf }}-linux-x86_64.zip' > checksums
        sha256sum -c checksums
        unzip protoc-${{ matrix.protobuf }}-linux-x86_64.zip -d /usr/local
    - name: Test plugin
      working-directory: main
      run: make test-plugin
    # dependencies for conformance tests
    - name: Checkout protobuf repo
      uses: actions/checkout@v2
      with:
        repository: protocolbuffers/protobuf
        ref: v${{ matrix.protobuf }}
        path: protobuf
    # we want to cache the conformance/conformance-test-runner binary
    # but the cache action only supports directory paths
    - name: Cache conformance-test-runner
      uses: actions/cache@v1
      with:
        path: protobuf/conformance/
        key: ${{ runner.os }}-pb-${{ matrix.protobuf }}-conformance-test-runner
    - name: Test conformance
      working-directory: main
      run: make test-conformance
